#!/usr/bin/env python3
"""Generate the Homebrew formula for a release of the prebuilt ingram-check binary.

The formula installs the self-contained PyInstaller bundle attached to each
GitHub release rather than building a Python virtualenv. This sidesteps
Homebrew's network-isolated install sandbox entirely: the bundle already
contains Python and every dependency (click, pikepdf+qpdf, PyMuPDF+MuPDF,
pillow, numpy, ...), so the user's machine compiles nothing and needs no Python.

PyInstaller runs in one-folder mode, so each release tarball expands to a
directory containing the `ingram-check` executable plus an `_internal/` folder
of bundled libraries. The formula installs the whole directory into `libexec`
and symlinks the executable into `bin`; PyInstaller resolves `_internal`
relative to the executable's real path, so the symlink works.

This script is pure (no network): the release workflow computes each tarball's
sha256 from the build artifacts and passes them in, which avoids racing against
GitHub release/CDN propagation.

Usage:
    python scripts/update_homebrew_formula.py \
        --version 0.1.7 \
        --repo saggingmeniscus/ingram-check \
        --formula path/to/Formula/ingram-check.rb \
        --sha macos-arm64=<sha256> \
        --sha macos-x86_64=<sha256> \
        --sha linux-x86_64=<sha256> \
        --sha linux-arm64=<sha256>
"""

from __future__ import annotations

import argparse
import sys

# target -> (homebrew os block, homebrew cpu block). The asset name is
# ingram-check-<target>.tar.gz and must match the release workflow's matrix.
TARGETS = {
    "macos-arm64": ("on_macos", "on_arm"),
    "macos-x86_64": ("on_macos", "on_intel"),
    "linux-arm64": ("on_linux", "on_arm"),
    "linux-x86_64": ("on_linux", "on_intel"),
}

ASSET_URL = "https://github.com/{repo}/releases/download/v{version}/ingram-check-{target}.tar.gz"


def parse_sha(value: str) -> tuple[str, str]:
    target, _, sha = value.partition("=")
    if target not in TARGETS:
        raise argparse.ArgumentTypeError(
            f"unknown target '{target}'; expected one of {', '.join(TARGETS)}"
        )
    if len(sha) != 64 or not all(c in "0123456789abcdef" for c in sha):
        raise argparse.ArgumentTypeError(f"'{target}' sha256 is not a 64-char hex digest")
    return target, sha


def cpu_block(repo: str, version: str, target: str, sha: str, indent: str) -> str:
    _, cpu = TARGETS[target]
    url = ASSET_URL.format(repo=repo, version=version, target=target)
    return f'{indent}{cpu} do\n{indent}  url "{url}"\n{indent}  sha256 "{sha}"\n{indent}end'


def os_block(repo: str, version: str, os_name: str, shas: dict[str, str]) -> str | None:
    cpu_blocks = [
        cpu_block(repo, version, target, shas[target], "    ")
        for target in TARGETS
        if TARGETS[target][0] == os_name and target in shas
    ]
    if not cpu_blocks:
        return None
    body = "\n\n".join(cpu_blocks)
    return f"  {os_name} do\n{body}\n  end"


def render_formula(repo: str, version: str, shas: dict[str, str]) -> str:
    os_blocks = [
        block
        for os_name in ("on_macos", "on_linux")
        if (block := os_block(repo, version, os_name, shas)) is not None
    ]
    platform_section = "\n\n".join(os_blocks)
    return f"""\
# This file is generated by scripts/update_homebrew_formula.py in
# {repo}. Do not edit by hand; edit the generator instead.
class IngramCheck < Formula
  desc "Ingram Lightning Source PDF compliance checker and fixer"
  homepage "https://github.com/{repo}"
  version "{version}"
  license "MIT"

{platform_section}

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"ingram-check"
  end

  test do
    assert_match "Usage", shell_output("#{{bin}}/ingram-check --help")
  end
end
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="released version, e.g. 0.1.7")
    parser.add_argument(
        "--repo", default="saggingmeniscus/ingram-check", help="owner/name of the source repo"
    )
    parser.add_argument("--formula", required=True, help="path to ingram-check.rb to write")
    parser.add_argument(
        "--sha",
        action="append",
        type=parse_sha,
        default=[],
        metavar="TARGET=SHA256",
        help="repeatable; one of: " + ", ".join(TARGETS),
    )
    args = parser.parse_args()

    shas = dict(args.sha)
    if not shas:
        parser.error("at least one --sha TARGET=SHA256 is required")

    formula = render_formula(args.repo, args.version, shas)
    with open(args.formula, "w") as fh:
        fh.write(formula)
    print(
        f"Wrote {args.formula} for {args.version} "
        f"({len(shas)} platform(s): {', '.join(sorted(shas))})",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
